/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, EventLogTestCreateDevice)
#endif

NTSTATUS
EventLogTestCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Initialize the context.
        //
        deviceContext->PrivateDeviceData = 0;


        DEVICE_OBJECT* devobj = WdfDeviceWdmGetDeviceObject(device);
        USHORT dump_size = 200; //DumpDataSize should be aligned to sizeof(ULONG)
        UCHAR size = (UCHAR)(sizeof(IO_ERROR_LOG_PACKET) + dump_size);
        IO_ERROR_LOG_PACKET* log = (IO_ERROR_LOG_PACKET*)IoAllocateErrorLogEntry(devobj, size);
        if(NULL !=log)
        {
            log->MajorFunctionCode = 0xFF;  // (optional)
            log->RetryCount = 0xFF;
            log->DumpDataSize = sizeof(ULONG);
            log->ErrorCode = STATUS_INTERNAL_ERROR; //shown on message %1, all followed string are printed in %2 ~ %n
            log->EventCategory=2;
            log->FinalStatus = STATUS_CRC_ERROR;    //real NT_STATUS code returned to OS or from API? (optional)
            log->IoControlCode = 0x12345678;        //current IOCTL code of this error? (optional)
            log->NumberOfStrings = 1;               //how many unicode strings following after dump data?
            log->SequenceNumber=0x28825252;         //seq no. of current IRP (optional)
            log->StringOffset = sizeof(IO_ERROR_LOG_PACKET) + log->DumpDataSize;
            log->UniqueErrorValue = 0x23939889;     //unique error code defined by driver.  (optional)

            UCHAR *ptr = ((UCHAR*)log) + log->StringOffset;
            RtlCopyMemory(ptr, L"My Test EventLog", wcslen(L"My Test EventLog") * sizeof(WCHAR));
            IoWriteErrorLogEntry(log);
            //IoFreeErrorLogEntry(log); //log entry will be freed in IoWriteErrorLogEntry();
        }
        status = STATUS_INTERNAL_ERROR;
    }
    return status;

#if 0
        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_EventLogTest,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = EventLogTestQueueInitialize(device);
        }
    }

    return status;
#endif
}
